nome = input('Escreva seu nome completo:')
nome2 = nome.lower()
nome3 = nome2.count('a')
nome4 = nome2.count('e')
nome5 = nome2.count('i')
nome6 = nome2.count('o')
nome7 = nome2.count('u')
print('Número de vogais em seu nome: ', nome3+nome4+nome5+nome6+nome7)